# Generated by Django 4.1 on 2022-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='happy',
            name='image',
            field=models.ImageField(default=1, upload_to='appkiimage'),
            preserve_default=False,
        ),
    ]
