# Generated by Django 4.1 on 2022-09-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_happy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('age', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('discription', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='appkiimage')),
            ],
        ),
    ]
