# Generated by Django 4.1 on 2022-09-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_complaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='user',
            new_name='name',
        ),
    ]
