# Generated by Django 4.1 on 2022-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_complaints_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='discription',
            field=models.TextField(),
        ),
    ]
